--liquibase formatted sql

-- ══════════════════════════════════════════════════════════════
-- 016: Окрема сутність для міжнародних стажувань.
-- ──────────────────────────────────────────────────────────────
-- Раніше критерій FOREIGN_INTERNSHIP помилково нараховувався з
-- qualification_improvements (за полем country != "Україна").
-- Це некоректно — курси підвищення кваліфікації нараховуються
-- лише за credits, а закордонне стажування — окрема активність.
--
-- Створюємо окрему таблицю foreign_internships на вкладці
-- "Інші досягнення" (поряд з academic_mobilities, open_lessons,
-- methodological_experiments). Існуючі дані з
-- qualification_improvements.country НЕ переносяться — поле там
-- залишається інформативним.
-- ══════════════════════════════════════════════════════════════

--changeset teacherlicence:016-create-foreign-internships splitStatements:true
--comment: Створює таблицю foreign_internships
CREATE TABLE foreign_internships (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id   BIGINT,
    program_name TEXT,
    institution  TEXT,
    country      VARCHAR(255),
    date_from    DATE,
    date_to      DATE,
    description  TEXT,
    notes        TEXT,
    document_url TEXT,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255)
);

--changeset teacherlicence:016-foreign-internships-fk splitStatements:true
--comment: FK на teachers (з ON DELETE CASCADE як в інших аудит-сутностях)
ALTER TABLE foreign_internships
    ADD CONSTRAINT fk_foreign_internships_teacher
    FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE CASCADE;

--changeset teacherlicence:016-foreign-internships-idx splitStatements:true
--comment: Індекс на teacher_id для швидкого пошуку записів викладача
CREATE INDEX idx_foreign_internships_teacher_id ON foreign_internships(teacher_id);
